name: CI Tests

on:
  pull_request:
    branches: ["main", "apartments"]
  push:
    branches: ["main", "apartments"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run: cd api && node server.js &

      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:5000
      
      - name: Start frontend
        run: npm run dev &
      
      - name: Wait for frontend
        run: npx wait-on http://127.0.0.1:5173

      # --- UNIT TESTS ---
      - name: Run Unit Tests
        run: npm run test:unit

      # --- POSTMAN API TESTS ---
      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run ./tests/postman/collection.json

      # --- PLAYWRIGHT E2E TESTS ---
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npm run test:e2e
